<?php
/**
 * Auto generated by prado-cli.php on 2013-07-27 08:05:08.
 */
class AprobacionesWSRecord extends TActiveRecord
{
	const TABLE='aprobaciones_ws';

	public $codigo;
	public $fecha;
        public $modulo;
        public $referencia;
	public $id_aprobacion;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>