<?php
/**
 * Auto generated by prado-cli.php on 2013-07-23 09:31:59.
 */
class AseguradorasRecord extends TActiveRecord
{
	const TABLE='aseguradoras';

	public $IdAseguradora;
	public $NmAseguradora;
        
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>