<?php
/**
 * Auto generated by prado-cli.php on 2013-07-23 09:32:16.
 */
class ConductoresRecord extends TActiveRecord
{
	const TABLE='conductores';

	public $IdConductor;
	public $Nombre;
	public $Apellido1;
	public $Apellido2;
	public $IdCiudad;
	public $Direccion;
	public $Barrio;
	public $TelConductor;
	public $Ext1;
	public $TelConductor2;
	public $Ext2;
	public $Celular;
	public $OtroCom;
	public $Email;
	public $Libreta;
	public $LicenciaConductor;
	public $Categoria;
	public $Senales;
	public $Alias;
	public $NmRefPersonal;
	public $TelRef;
	public $DirRef;
	public $Fhingreso;
	public $TpIdConductor;
	public $PlacaPred;
	public $FhVenceLic;
	public $FhNac;
	public $ConductorInactivo;
	public $ImagenConductor;
        public $NroSeguridadSocial;
        public $FhVenceSeguridadSocial;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>