<?php
/**
 * Auto generated by prado-cli.php on 2013-07-23 09:31:19.
 */
class DespachosRecord extends TActiveRecord
{
	const TABLE='despachos';

	public $IdManifiesto;
	public $OrdDespacho;
	public $Tipo;
	public $FhExpedicion;
	public $FhCumplidos;
	public $IdVehiculo;
	public $IdConductor;
	public $IdRuta;
	public $IdCiudadOrigen;
	public $IdCiudadDestino;
	public $Estado;
	public $Remesas;
	public $Unidades;
	public $KilosReales;
	public $KilosVol;
	public $FleteCobra;
	public $ManejoCobra;
	public $FleteCE;
	public $ManejoCE;
	public $VrFlete;
	public $VrAnticipo;
	public $VrDctoPapeleria;
	public $VrDctoSeguridad;
	public $VrDctoCargue;
	public $VrDctoEstampilla;
	public $VrFleteAdicional;
	public $VrDctoIndCom;
	public $VrDctoRteFte;
	public $VrOtrosDctos;
	public $SaldoDesp;
	public $TotalViaje;
	public $CO;
	public $Observaciones;
	public $TRecaudo;
	public $VrDeclaradoTotal;
	public $ruta1;
	public $Kilometrostotal;
	public $tarifaflete;
	public $ciudadtramoorigen;
	public $ciudadtramodestino;
	public $kilomtramoorigen;
	public $kilomtramodestino;
	public $ManElectronico;
	public $NmConductor;
	public $Cerrado;
	public $Liquidado;
	public $IdUsuario;
	public $IdEmpresa;
	public $Exportado;
	public $LugarPago;
	public $FhPagoSaldo;
	public $PagoCargue;
	public $PagoDescargue;
	public $Estado1;
	public $IdRuta1Min;
	public $IdRuta2Min;
	public $AbonosCE;
	public $FletesNoCancelados;
	public $EnviadoMT;
        public $EnviadoGuia;
        public $TotalCE;
        public $FleteContado;
        public $ManejoContado;
        public $FleteCorriente;
        public $ManejoCorriente;
        public $FleteCETotal;
        public $ManejoCETotal;
        public $ExportadoContabilidad;
        public $CiudadOrigen; //Array de tipo (Ciudad)
        public $CiudadDestino; //Array de tipo (Ciudad)        
        public static $RELATIONS = array(
            'CiudadOrigen' => array(self::BELONGS_TO, 'CiudadesRecord', 'IdCiudadOrigen'),
            'CiudadDestino' => array(self::BELONGS_TO, 'CiudadesRecord', 'IdCiudadDestino'),
        );
        
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
        
        public function DevDespachosPendientes() {
            $strSql = "SELECT despachos.OrdDespacho, ManElectronico, IdManifiesto, EnvioPersona, EnvioVehiculo, EnvioGuias, EnvioManifiesto,
                              ExpedirRemesas, ExpedirManifiesto
                        FROM despachos
                        LEFT JOIN despachos_control_mt ON despachos.OrdDespacho = despachos_control_mt.OrdDespacho
                        WHERE FhExpedicion >= '2013/07/10' AND IdManifiesto > 0 AND Enviado = 0";
            $arDespachos = DespachosRecord::finder('DespachosExtRecord')->findAllBySql($strSql);            
            return $arDespachos;            
        }
}
class DespachosExtRecord extends DespachosRecord {
    	public $EnvioPersona;
        public $EnvioVehiculo;
        public $EnvioGuias;
        public $EnvioManifiesto;
        public $ExpedirRemesas;
        Public $ExpedirManifiesto;
}
?>