<?php
/**
 * Auto generated by prado-cli.php on 2013-07-27 11:23:30.
 */
class DespachosControlMTRecord extends TActiveRecord
{
	const TABLE='despachos_control_mt';

	public $OrdDespacho;
	public $ManifiestoInterno;
	public $EnvioPersona;
	public $EnvioConductor;
	public $EnvioEmpresa;
	public $EnvioVehiculo;
        public $Enviado;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>