<?php
/**
 * Auto generated by prado-cli.php on 2013-07-27 08:05:08.
 */
class ErroresWSRecord extends TActiveRecord
{
	const TABLE='errores_ws';

	public $codigo;
	public $fecha;
	public $tipo;
        public $modulo;
        public $referencia;
	public $error;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>