<?php
/**
 * Auto generated by prado-cli.php on 2013-07-23 09:31:47.
 */
class GuiasRecord extends TActiveRecord
{
	const TABLE='guias';

	public $Guia;
	public $CR;
	public $Remitente;
	public $IdCliente;
	public $DocCliente;
	public $NmDestinatario;
	public $DirDestinatario;
	public $TelDestinatario;
	public $IdCiuDestino;
	public $IdRuta;
	public $FhEntradaBodega;
	public $FhEntregaMercancia;
	public $VrDeclarado;
	public $VrFlete;
	public $VrManejo;
	public $Unidades;
	public $KilosReales;
	public $KilosFacturados;
	public $KilosVolumen;
	public $Estado;
	public $IdFactura;
	public $IdDespacho;
	public $Observaciones;
	public $COIng;
	public $Cuenta;
	public $Cliente;
	public $Recaudo;
	public $Orden;
	public $EmpaqueRef;
	public $RelCliente;
	public $IdCiuOrigen;
	public $IdRelEntrega;
	public $FhDescargada;
	public $IdFactura2;
        public $IdFactura3;
        public $Abonos;
        public $GuiaTipo;
        public $TipoCobro;
	public $Despachada;
	public $TpServicio;
	public $IdTpCtaFlete;
	public $IdTpCtaManejo;
	public $CPorte;
	public $Entregada;
	public $Descargada;
	public $Anulada;
	public $GuiFac;
	public $Facturada;
	public $Facturada2;
        public $Facturada3;
	public $IdUsuario;
	public $IdPlanillaFactura;
	public $IdEmpresa;
	public $Relacionada;
	public $EnNovedad;
	public $FhRegistroEntrega;
        public $ActualizadoWebServices;
        public $ExpedirRemesaWS;
        public $Exportado; 
        public $ExportadaCartera;
        public $ClienteRemitente; //Array de tipo (Tercero)
        public static $RELATIONS = array(
            'ClienteRemitente' => array(self::BELONGS_TO, 'TercerosRecord', 'Cuenta'),            
        );        
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
        
        public function DevClientesGuias($intOrdDespacho) {
            $strSql = "SELECT guias.Cuenta
                        FROM guias                        
                        WHERE IdDespacho = " . $intOrdDespacho . "
                        GROUP BY Cuenta";
            
            $arGuias = GuiasRecord::finder()->findAllBySql($strSql);            
            return $arGuias;            
        }        
}
?>