<?
		$aux_buscar_autoriz="<?xml version='1.0' encoding='ISO-8859-1' ?>
				<root>
				 <acceso>
				  <username>LOGI@2446LOGICUARTAS</username>
				  <password>Lo15me_A24</password>
				 </acceso>
				 <solicitud>
				  <tipo>3</tipo>
				  <procesoid>4</procesoid>
				 </solicitud>
				 <variables>
				    ingresoid				
				 </variables>
				 <documento>
				  <NUMMANIFIESTOCARGA>".$_SESSION['MFTO']."</NUMMANIFIESTOCARGA>
				 </documento>
				</root>";
?>